default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: foodkart_development
  username: ubuntu
  password: yourpassword
  host: localhost

test:
  <<: *default
  database: foodkart_test
  username: ubuntu
  password: yourpassword
  host: localhost

production:
  <<: *default
  database: foodkart_production
  username: ubuntu
  password: Shyamansi#844
  host: localhost

