default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Shyamansi#844
  host: localhost
  pool: 5

development:
  <<: *default
  database: hotel_booking_app_development

test:
  <<: *default
  database: hotel_booking_app_test

production:
  <<: *default
  database: hotel_booking_app_production
  username: your_production_username
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
